- name: Install MySQL Server 8.0.x
  hosts: mysql
  become: yes
  tasks: #Install MySQL Server 8.0.x
    - name: Install MySQL Server 8.0.x
      ansible.builtin.package:
        name: mysql-server
        state: installed
    - name: Start MySQL Service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: Get MySQL version with non-default credentials
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql.daws82.online
      register: mysql_info
    - name: Print the output
      ansible.builtin.debug:
        msg: "MySql info: {{mysql_info}}"