- name: Install MySQL Server 8.0.x
  hosts: mysql
  become: yes
  tasks: #Install MySQL Server 8.0.x
    - name: Install MySQL Server 8.0.x
      ansible.builtin.package:
        name: mysql-server
        state: installed
    - name: Start MySQL Service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes